# Etapa de construcción
FROM node:14.16.0 as build-step
WORKDIR /app
COPY ./client/package.json /app
RUN npm install
COPY . /app
RUN npm run build

#Etapa de producción
FROM nginx:1.24.0-alpine
COPY --from=build-step /app/dist/my-store-api /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
